name: Test

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:stable-dind
        options: --privileged
        env:
          DOCKER_DRIVER: overlay2
          DOCKER_HOST: tcp://localhost:2375
          DOCKER_TLS_CERTDIR: ""
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: |
          cp .env.testing .env
          rm docker-compose.yml
          cp docker-compose.testing.yml docker-compose.yml

          curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          /usr/local/bin/composer update --ignore-platform-req=ext-gd --ignore-platform-req=ext-intl --ignore-platform-req=ext-iconv

          ./docker/testing/bin/sail up -d
          docker exec laravel.test composer update
          docker exec laravel.test npm install
          docker exec laravel.test npm run build
          docker exec laravel.test php artisan test --env=testing
