name: Test

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:stable-dind
        options: --privileged
        env:
          DOCKER_DRIVER: overlay2
          DOCKER_HOST: tcp://localhost:2375
          DOCKER_TLS_CERTDIR: ""
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: |
          cp .env.testing .env
          ./docker/testing/bin/sail up -d
          docker exec cyanfox-poll-laravel.test-1 composer update
          docker exec cyanfox-poll-laravel.test-1 npm install
          docker exec cyanfox-poll-laravel.test-1 npm run build
          docker exec cyanfox-poll-laravel.test-1 php artisan test --env=testing
